[package]
name = "digital_identity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "23.0.0"

[dev-dependencies]
soroban-sdk = { version = "23.0.0", features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]